### PR TITLE
Fix for #9

### PR DESCRIPTION
**Pull request by RobinJadoul**
I'm not sure if it's a problem, but for it to work, I had to remove the `&jsonp=?` from the http request url

### CODE REVIEW

**Comment by Technici4n** [comment]
The jsonp is necessary to circumvent cross-origin request policies. It requests a JS script instead of plain data. If I recall correctly, the problem did happen, but only in production.

**Comment by Technici4n** [comment]
Nevermind, the problems request doesn't use jsonp and it works.

**Comment by Technici4n** [comment]
Nevermind, the website works for me. It was just Brave automatically upgrading to HTTPS... Closed and #9 too ! Nonetheless, thanks for the promise fix. 😄

**Comment by RobinJadoul** [comment]
The problem was that it didn't fix the problem on chromium without removing the jsonp...
Not quite sure why

**Comment by Technici4n** [comment]
Manually changing Lucas's username to the correct one fixed the problem, so I think the bug comes from the updating code. If I was to bet on something, I'd say there is a JS error caught somewhere because of an "incomplete" JSON object. I'm going to investigate...
(The problem actually appeared again for me too: the tracker gets stuck on people with a wrong username. The good news is that it's very easy to replicate locally: create an account with a wrong CF username locally.)

**Comment by RobinJadoul** [comment]
In my tests, the promise for the missing username was never resolved nor rejected with jsonp, if I recall correctly

**Pull request closed without merging**
